#include "../Headers/portfolio.h"
#include <iostream>
#include <iomanip>
#include <sstream>
#include <numeric>
#include <algorithm>
#include <cmath>
#include <stdexcept>

// Constructor for portfolio class

Portfolio::Portfolio(std::string name, int numSimulations, int numDays)
    : name(name),
      numSimulations(numSimulations),
      numDays(numDays),
      metrics{},
      simulated(false)
{
    portfolioReturns.reserve(numSimulations);
}

void Portfolio::addStock(const std::string &sName, double initialPrice, double vol, double weight)
{
    StockEntry entry{Stock(sName, initialPrice, vol), weight}; // Forming Structure
    entries.push_back(entry);                                  // pushing each structure to the vector
}

// Validate the weights

void Portfolio::validateWeights() const
{
    double total = 0;
    for (const auto &e : entries)
    {
        total += e.weight;
    }

    if (std::abs(total - 1.0) > 0.01)
    {
        std::cout << "[WARNING] Weights sum to: " << std::fixed << std::setprecision(4) << total << "[Expected: 1.0]. The result may be misleading.\n";
    }
}

// Blended Return = Summation ( Stock Return * Weight )

double Portfolio::blendReturns(const std::vector<double> &simReturns) const
{
    double blended = 0;
    for (size_t i = 0; i < entries.size(); i++)
    {
        blended = simReturns[i] * entries[i].weight;
    }
    return blended;
}

void Portfolio::simulatePortfolio()
{
    if (entries.empty())
    {
        std::cerr << "No stocks added.\n";
        return;
    }

    validateWeights();

    portfolioReturns.clear();
    portfolioReturns.reserve(numSimulations);

    std::cout << "SImulating Portfolio \"" << name << "\" (" << entries.size() << " stocks, " << numSimulations << " runs)";
    std::cout.flush();

    for (int run = 0; run < numSimulations; run++)
    {

        if (run % 100 == 0)
        {
            std::cout << ".";
            std::cout.flush();
        }

        std::vector<double> runReturns;
        runReturns.reserve(entries.size());

        for (auto &entry : entries)
        {
            std::vector<double> path = entry.stock.generatePricePath(numDays);
            double initP = entry.stock.getInitialPrice();
            double finalP = path.back();
            double ret = (finalP - initP) / initP;
            runReturns.push_back(ret);
        }

        double portfolioRet = blendReturns(runReturns);
        portfolioReturns.push_back(portfolioRet);
    }

    std::cout << "Finished!\n";

    // Expected Return
    double sumR = std::accumulate(portfolioReturns.begin(), portfolioReturns.end(), 0);
    metrics.expectedReturn = sumR / portfolioReturns.size();

    // Volatility
    double sumSq = 0;
    for (double r : portfolioReturns)
    {
        sumSq += (r - metrics.expectedReturn) * (r - metrics.expectedReturn);
    }
    metrics.volatility = std::sqrt(sumSq / portfolioReturns.size());

    // Loss Probability
    int lossCount = 0;
    for (double r : portfolioReturns)
    {
        if (r < 0)
            lossCount++;
    }
    metrics.lossProbability = static_cast<double>(lossCount) / portfolioReturns.size();

    // Worst / best case
    metrics.worstCase = *std::min_element(portfolioReturns.begin(), portfolioReturns.end());
    metrics.bestCase = *std::max_element(portfolioReturns.begin(), portfolioReturns.end());

    // Maximum Drawdown
    double peak = 0, worstDD = 0;
    double cumulative = 0;
    for (double r : portfolioReturns)
    {
        cumulative += r / portfolioReturns.size(); // mean
        if (cumulative > peak)
            peak = cumulative;
        double dd = (peak > 0) ? (cumulative - peak) / peak : 0;
        if (dd < worstDD)
            worstDD = dd;
    }
    metrics.maxDrawdown = metrics.worstCase;
    metrics.avgFinalPrice = 1 + metrics.expectedReturn;

    simulated = true;
}



// This part was generated by AI to show the output (I'll later change it accordingly)

// ------------------------------------------------------------------
// Simplified printHoldings() — Raw text output
// ------------------------------------------------------------------
void Portfolio::printHoldings() const
{
    std::cout << "\n--- CURRENT PORTFOLIO RAW HOLDINGS ---\n";
    for (const auto &e : entries)
    {
        std::cout << "Asset: " << e.stock.getName()
                  << " | Price: " << e.stock.getInitialPrice()
                  << " | Volatility: " << e.stock.getVolatility()
                  << " | Weight: " << e.weight << "\n";
    }
    std::cout << "--------------------------------------\n";
}

// ------------------------------------------------------------------
// Simplified printReport() — Raw metrics dump
// ------------------------------------------------------------------
void Portfolio::printReport() const
{
    if (!simulated)
    {
        std::cout << "Error: Run simulatePortfolio first.\n";
        return;
    }

    std::cout << "\n--- SIMULATION RISK METRICS RESULTS ---\n";
    std::cout << "Portfolio Name: " << name << "\n";
    std::cout << "Expected Return: " << metrics.expectedReturn << "\n";
    std::cout << "Volatility: " << metrics.volatility << "\n";
    std::cout << "Loss Probability: " << metrics.lossProbability << "\n";
    std::cout << "Worst Case Return: " << metrics.worstCase << "\n";
    std::cout << "Best Case Return: " << metrics.bestCase << "\n";
    std::cout << "Max Drawdown Proxy: " << metrics.maxDrawdown << "\n";
    std::cout << "Normalized Avg Final Value: " << metrics.avgFinalPrice << "\n";
    std::cout << "-------------------------------------------\n";
}

// Simple Accessor Getters to keep compiler happy
const std::vector<double> &Portfolio::getPortfolioReturns() const { return portfolioReturns; }
RiskMetrics Portfolio::getMetrics() const { return metrics; }
std::string Portfolio::getName() const { return name; }
int Portfolio::getStockCount() const { return entries.size(); }